apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../projects
  - ../../environments/dev
  - dev-resource-governance.yaml
  - service-a-identity.yaml
  - service-a.yaml
