apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-a
  labels:
    app.kubernetes.io/name: service-a
    app.kubernetes.io/instance: service-a-dev
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: golden-path-platform
automountServiceAccountToken: false
